from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime

class PDFReportGenerator:
    """
    Generates structured orthopedic reports in PDF format.
    """

    def __init__(self, output_path: str):
        self.output_path = output_path

    def generate(self, data: dict):
        """
        data: dictionary containing report details.
        """
        c = canvas.Canvas(self.output_path, pagesize=letter)
        width, height = letter

        # Header
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, "ORTHOVISION AI - Orthopedic Analysis Report")

        c.setFont("Helvetica", 10)
        c.drawString(50, height - 70, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        c.drawString(50, height - 85, f"Patient ID: {data.get('patient_id', 'N/A')}")

        # Fracture Analysis
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, height - 120, "Fracture Analysis")
        c.setFont("Helvetica", 10)
        c.drawString(70, height - 140, f"Detected: {data.get('fracture_detected', 'No')}")
        c.drawString(70, height - 155, f"Displacement: {data.get('displacement', '0')} mm")
        c.drawString(70, height - 170, f"Angulation: {data.get('angulation', '0')} degrees")

        # Measurements
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, height - 210, "Clinical Measurements")
        y = height - 230
        for key, value in data.get('measurements', {}).items():
            c.setFont("Helvetica", 10)
            c.drawString(70, y, f"{key}: {value}")
            y -= 15

        # Footer
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(50, 50, "This report was automatically generated by OrthoVision AI and should be reviewed by a specialist.")

        c.save()
